version: '3'

networks:

  text-format-dashboard-online:
    external: false

services:

  text-format-dashboard-online-api:

    container_name: text-format-dashboard-online-api

    image: textformatdashboard.online/text-format-dashboard-api-java:latest

    restart: unless-stopped

    networks:
      - text-format-dashboard-online

    ports:

      - "44444:8080"
